/* eslint-disable unicorn/prefer-module */
import { Module, ValidationPipe } from '@nestjs/common'
import { APP_PIPE } from '@nestjs/core'
import { GraphQLModule } from '@nestjs/graphql'
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius'
import { LocationModule } from '@seek-n-grill/api/feature-location'
import { UserModule } from '@seek-n-grill/api/feature-user'
import * as path from 'node:path'

const validationProvider = {
  provide: APP_PIPE,
  useValue: new ValidationPipe()
}

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql')
    }),
    UserModule,
    LocationModule
  ],
  providers: [validationProvider]
})
export class AppModule {}
